import * as Joi from 'joi';

export const validationSchema = Joi.object({
  NODE_ENV: Joi.string()
    .valid('development', 'test', 'production')
    .default('development'),
  PORT: Joi.number().default(3000),
  DATABASE_URL: Joi.string().uri().required(),
  JWT_ACCESS_SECRET: Joi.string().min(32).required(),
  JWT_ACCESS_EXPIRES_IN: Joi.string().default('15m'),
  JWT_REFRESH_TTL_SECONDS: Joi.number().integer().positive().default(604800),
  AUTH_ACCESS_TOKEN_COOKIE_NAME: Joi.string().default('qedu_access_token'),
  AUTH_REFRESH_TOKEN_COOKIE_NAME: Joi.string().default('qedu_refresh_token'),
  AUTH_COOKIE_DOMAIN: Joi.string().allow('').optional(),
  AUTH_COOKIE_SECURE: Joi.boolean().truthy('true').falsy('false').default(true),
  AUTH_COOKIE_SAMESITE: Joi.string()
    .valid('lax', 'strict', 'none')
    .default('lax'),
  SMTP_HOST: Joi.string().required(),
  SMTP_PORT: Joi.number().integer().positive().default(587),
  SMTP_USER: Joi.string().required(),
  SMTP_PASSWORD: Joi.string().required(),
  SMTP_SECURE: Joi.boolean().truthy('true').falsy('false').default(false),
  SMTP_FROM: Joi.string().email().required(),
  ZOOM_ENABLED: Joi.boolean().truthy('true').falsy('false').optional(),
  ZOOM_ACCOUNT_ID: Joi.when('ZOOM_ENABLED', {
    is: true,
    then: Joi.string().required(),
    otherwise: Joi.string().allow('').optional(),
  }),
  ZOOM_CLIENT_ID: Joi.when('ZOOM_ENABLED', {
    is: true,
    then: Joi.string().required(),
    otherwise: Joi.string().allow('').optional(),
  }),
  ZOOM_CLIENT_SECRET: Joi.when('ZOOM_ENABLED', {
    is: true,
    then: Joi.string().required(),
    otherwise: Joi.string().allow('').optional(),
  }),
  ZOOM_API_BASE_URL: Joi.string().uri().default('https://api.zoom.us/v2'),
  ZOOM_OAUTH_URL: Joi.string().uri().default('https://zoom.us/oauth/token'),
  CORS_ALLOWED_ORIGINS: Joi.string().allow('').optional(),
  ALLOWED_ORIGINS: Joi.string().allow('').optional(),
  FILE_STORAGE_DRIVER: Joi.string().valid('local').default('local'),
  LOCAL_STORAGE_ROOT: Joi.string().allow('').optional(),
  FILE_STORAGE_PUBLIC_URL: Joi.string().uri().allow('').optional(),
  FILE_STORAGE_PUBLIC_ROOT: Joi.string().allow('').default('/storage'),
  STRIPE_SECRET_KEY: Joi.string().allow('').optional(),
  STRIPE_PUBLISHABLE_KEY: Joi.string().allow('').optional(),
  STRIPE_WEBHOOK_SECRET: Joi.string().allow('').optional(),
  STRIPE_CLIENT_ID: Joi.string().allow('').optional(),
  STRIPE_API_VERSION: Joi.string().allow('').optional(),
  STRIPE_CURRENCY: Joi.string().lowercase().length(3).default('usd'),
  STRIPE_SUCCESS_URL: Joi.string().allow('').optional(),
  STRIPE_CANCEL_URL: Joi.string().allow('').optional(),
  STRIPE_PORTAL_RETURN_URL: Joi.string().allow('').optional(),
  PLATFORM_FEE_PERCENT: Joi.number().min(0).max(100).default(10),
  SUPER_ADMIN_EMAIL: Joi.string().email({ tlds: false }).allow('').optional(),
  SUPER_ADMIN_PASSWORD: Joi.string().min(8).allow('').optional(),
  SUPER_ADMIN_FIRST_NAME: Joi.string().allow('').default('Super'),
  SUPER_ADMIN_LAST_NAME: Joi.string().allow('').default('Admin'),
});
